planner_server:
  ros__parameters:
    planner_plugin: "nav2_navfn_planner/NavfnPlanner"
    use_sim_time: False
    expected_planner_frequency: 20.0
    planner_server:
      costmap_topic: "global_costmap/costmap"
      planner_plugin: "nav2_navfn_planner/NavfnPlanner"
      planner_frequency: 1.0
      planner_patience: 5.0

controller_server:
  ros__parameters:
    controller_plugin: "dwb_core/DWBLocalPlanner"
    use_sim_time: False
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001
    progress_checker_plugin: "progress_checker"
    goal_checker_plugin: "goal_checker"
    controller_server:
      costmap_topic: "local_costmap/costmap"
      controller_frequency: 20.0
      controller_patience: 5.0

bt_navigator:
  ros__parameters:
    use_sim_time: False
    bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
    default_nav_to_pose_bt_xml: "navigate_w_replanning_and_recovery.xml"
    default_nav_through_poses_bt_xml: "navigate_w_replanning_and_recovery.xml"
    global_frame: "map"
    robot_base_frame: "base_link"
    odom_topic: "/odom"

waypoint_follower:
  ros__parameters:
    use_sim_time: False
    loop_rate: 20.0
    waypoint_task_executor_plugin: "waypoint_follower"

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: "map"
      robot_base_frame: "base_link"
      resolution: 0.05
      size_x: 100
      size_y: 100
      origin_x: -50.0
      origin_y: -50.0
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: "laser_scan_sensor"
        laser_scan_sensor:
          topic: "/scan"
          max_obstacle_height: 2.0
          clearing: True
          marking: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 10.0
        inflation_radius: 0.55

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: "odom"
      robot_base_frame: "base_link"
      resolution: 0.05
      size_x: 10
      size_y: 10
      origin_x: -5.0
      origin_y: -5.0
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: "laser_scan_sensor"
        laser_scan_sensor:
          topic: "/scan"
          max_obstacle_height: 2.0
          clearing: True
          marking: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 10.0
        inflation_radius: 0.55